import "./globals.css";
import type { Metadata } from "next";
import { Inter, Roboto, Open_Sans, Teko } from "next/font/google";
import Layout from "./_components/Layout";

const inter = Inter({ subsets: ["vietnamese"] });
const roboto = Teko({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Alexandre Barber Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className + " bg-slate-900"}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
