import "./globals.css";
import type { Metadata } from "next";
import {
  Inter,
  Roboto,
  Open_Sans,
  Teko,
  Barlow_Condensed,
  Poppins,
} from "next/font/google";
import Layout from "./_components/Layout";

const inter = Inter({ subsets: ["vietnamese"] });
const roboto = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Alexandre Barber Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
